### ISSUE TITLE
could not determine kind of name for C.TOX_SAVEDATA_*

### ISSUE THREAD

**Issue by xamino** [codedust/go-tox#1]
Hi!

I tried to build the wrapper for my own tests and ran into the following error with the current version:

```
> go install github.com/codedust/go-tox/examples
# github.com/codedust/go-tox
could not determine kind of name for C.TOX_SAVEDATA_TYPE
could not determine kind of name for C.TOX_SAVEDATA_TYPE_NONE
could not determine kind of name for C.TOX_SAVEDATA_TYPE_SECRET_KEY
could not determine kind of name for C.TOX_SAVEDATA_TYPE_TOX_SAVE
```

It also happens for my own code, not only for the provided examples. By checking out the recent version 7b5149395db568748313c513d9e24c39e0ac20c0 it works again. If you need any further info just ask, happy to help. Thanks for your work!

**Comment by codedust** [comment]
Hi!

Did you update toxcore to the latest version? These TOX_SAVEDATA constants have been added 18 days ago.

Also, I would recommend runnig the examples via `go run examples/example.go` rather then `go install`.

**Comment by xamino** [comment]
Indeed, my Toxcore was out of date. Sorry for the trivial problem and thanks!

**Comment by codedust** [comment]
No problem. Nice to hear it worked. ;)
