### ISSUE TITLE
Fatal error: tox/tox.h

### ISSUE THREAD

**Issue by nikolaev-dm** [codedust/go-tox#11]
Hi @codedust ,
I have problems compiling the library. It's a commented-out line. Why `Go` trying to implement it? Perhaps I what the not understand, but tell me that me to do in this case. Thanks

**Erorr Log:**
```
# github.com/codedust/go-tox
../../../GOPATH/src/github.com/codedust/go-tox/bindings.go:3:10: fatal error: tox/tox.h: No such file or directory
 //#include <tox/tox.h>
          ^~~~~~~~~~~
compilation terminated.
```

**Comment by codedust** [comment]
Did you install the `tox` C-library on your system? https://github.com/TokTok/c-toxcore

**Comment by nikolaev-dm** [comment]
Thanks for the answer. Indeed, the installation of this library solved the problem! It is a pity that this dependency is not described in the README

**Comment by codedust** [comment]
Yes, you're right. I've updated `README.md` to include some more verbose instructions. :)
