### ISSUE TITLE
Example.go doesn't seem to connect

### ISSUE THREAD

**Issue by xamino** [codedust/go-tox#2]
Hi, me again.

The current version of the go-tox wrapper doesn't seem to ever connect to the Tox network as it will never receive any friend requests since about early last week. My Tox version is current at this time. I tried replacing the bootstrap node but that doesn't seem to make a difference. Neither the examples nor my own code seems to connect successfully although no errors ever happen.

Tox has been updated on my system since the last update of go-tox. I tried to get the older package version again to check if the fault is in Tox but failed to do so (I'll never remove old package tars ever again :disappointed:   ).

If you could either confirm the problem or otherwise point me in the right direction I'd be very thankful.

Greetings!

**Comment by codedust** [comment]
Hmm. I just stated example.go and added its Tox ID in qTox (on the same computer). The friend request got accepted nearly immediately (using the latest version of toxcore).

How did you send the friend request (which Tox client, same or remote computer)? You may also test your client by adding my running instance of example.go `5f422f6ff7278a6c5bf928b4e07468b0f9df9cf3a3dc889f445cfde0deaf7f11b0c3039813d9`. I'll keep it running the next hours.

**Comment by xamino** [comment]
Interesting, it connects. I sent the request from the same computer (but have also tried an external client and another tox client on the same computer). Here is my package version information:

Name           : tox-git
Version        : r3420.67df1ab-1
Description    : Secure, configuration-free, P2P Skype replacement backend
Architecture   : x86_64
URL            : https://tox.im
Licenses       : GPL3
Groups         : None
Provides       : tox
Depends On     : libconfig>=1.4  libsodium>=1.0  libvpx  opus
Optional Deps  : qtox-git: qt-based Tox client [installed]
                 utox-git: lightweight Tox client [installed]
                 toxic-git: ncurses-based Tox client
Required By    : qtox-git  utox-git
Optional For   : None
Conflicts With : tox
Replaces       : tox
Installed Size : 427.00 KiB
Packager       : Unknown Packager
Build Date     : Fri 19 Jun 2015 03:44:05 PM CEST
Install Date   : Fri 19 Jun 2015 03:44:15 PM CEST
Install Reason : Explicitly installed
Install Script : No
Validated By   : None

If I'm reading this correctly it corresponds to this commit, which should make it up to date: https://github.com/irungentoo/toxcore/commit/67df1ab7ce6b6cb8103ddf73df814f685240a59c. No updates from go-tox, so I am kind of lost why it stopped working.

Just to be sure I'll try recloning go-tox and restarting Tox.

**Comment by codedust** [comment]
Strange. I also received the friend request:
`New friend request from ed284... With message: xamino here! Tox me maybe?`

Do you have a bootstap node or any firewall that blocks port 3389 running on the same machine as gotox?

**Comment by xamino** [comment]
After deactivating my firewall and rebooting it now works again. Strange because it worked previously even with the firewall on. Thank you for your help!

**Comment by codedust** [comment]
Great! I now disabled the local TCP server in the example. That could have been the problem.

**Comment by xamino** [comment]
Thanks, I've adopted that. Thank you for your support! Much appreciated.
