### ISSUE TITLE
Implement File Send

### ISSUE THREAD

**Issue by xamino** [codedust/go-tox#3]
Hi, me again.

I've now reached the point where I've implemented file receiving but now require the capability of file sending too. Based on [PROGRESS.md](https://github.com/codedust/go-tox/blob/master/PROGRESS.md]) and the available code this is not yet implemented.

You've stated that you were open for feature requests via issues, so here it is. I'll see if I can implement it myself if you do not have the time to yourself. However I am still new to Golang and this would be my first stint into C bindings via cgo, so if possible I'd like to avoid that. :sweat_smile: 

Thanks either way!

**Comment by xamino** [comment]
So I gave it a try and came up with the following. However I do not seem to be able to get it to compile / work or even test it. I'll post it here in the hope that it isn't all too wrong.

``` Go
/*
FileSend sends a file transmission request.
*/
func (t *Tox) FileSend(friendnumber uint32, fileKind ToxFileKind, filelength uint64, fileID uint8, filename string) (uint32, error) {
    if t.tox == nil {
        return 0, ErrBadTox
    }

    var cFileKind = C.TOX_FILE_KIND_DATA
    switch ToxFileKind(fileKind) {
    case TOX_FILE_KIND_AVATAR:
        cFileKind = C.TOX_FILE_KIND_AVATAR
    case TOX_FILE_KIND_DATA:
        cFileKind = C.TOX_FILE_KIND_DATA
    }

    cFilename := (*C.uint8_t)(&[]byte(filename)[0])

    var toxErrfileControl C.TOX_ERR_FILE_CONTROL
    n := C.tox_file_send(t.tox, (C.uint32_t)(friendnumber), cFileKind, (C.uint64_t)(length), (C.uint8_t)(fileID), cFilename, (C.size_t)(len(filename)), &toxErrfileControl)
    // check if all ok
    filenumber := uint32(n)
    if filenumber == math.MaxUint32 || ToxErrFileControl(toxErrfileControl) != TOX_ERR_FILE_CONTROL_OK {
        return 0, ErrFuncFail
    }
    return filenumber, nil
}

/*
FileSendChunk sends a file chunk to a friend.
*/
func (t *Tox) FileSendChunk(friendnumber uint32, filenumber uint32, position uint64, data []byte, length uint64) error {
    if t.tox == nil {
        return ErrBadTox
    }

    cData := (*C.uint8_t)(&data[0])

    var toxErrfileControl C.TOX_ERR_FILE_CONTROL
    success := C.tox_file_send_chunk(t.tox, (C.uint32_t)(friendnumber), (C.uint32_t)(filenumber), (C.uint64_t)(position), cData, (C.uint64_t)(length), &toxErrfileControl)
    if !bool(success) || ToxErrFileControl(toxErrfileControl) != TOX_ERR_FILE_CONTROL_OK {
        return ErrFuncFail
    }
    return nil
}
```

**Comment by codedust** [comment]
Thanks! I don't have much time atm but I'll give it a try this evening.

**Comment by xamino** [comment]
Fantastic, thank you very much!

**Comment by codedust** [comment]
Done. ;)
`tox_file_seek` and `tox_file_get_file_id` are still missing. Let me know when you need them.

**Comment by xamino** [comment]
Thank you very much, works like a charm. Except: if I check for errors on calling t.FileSendChunk(friendNumber, fileNumber, position, data) in onFileChunkRequest, I always get an error back, specifically the "Function Failed" error (both in my code and in the example.go file if you catch the return of the function). The file is correctly received and valid, I have checked that. Not critical but a small bug. :wink: 

Otherwise I think I have all the functionality I'll require from here on out, so you should be safe from me for now. Cheers!

**Comment by codedust** [comment]
Thanks for your bug report! The error is thrown because we try to call `FileSendChunk` with `len(data) == 0` when the file transfer is already completed. This is because `onFileChunkRequest` is called with a `length` of `0` when the file transfer is finished.

> If the length parameter is 0, the file transfer is finished, and the client's resources associated with the file number should be released. [...]
> For files with known size, Core will know that the transfer is complete after the last byte has been received, so it is not necessary (though not harmful) to send a zero-length chunk to terminate.
> -- tox.h

I updated example.go to comply with this specification.

**Comment by xamino** [comment]
Ah, so a bug on my side, specifically the user side. :stuck_out_tongue: I've modified my code accordingly, now it works perfectly.

Thanks again!

**Comment by codedust** [comment]
Hi! I found the time to add the missing C bindings. When updating, make sure to remove the unnecessary arguments from gotox.FileControl() (see [examples/example.go#L165](https://github.com/codedust/go-tox/blob/master/examples/example.go#L165)).

**Comment by xamino** [comment]
Thanks for the warning, I'll update my code now to stay up to date.

EDIT: Update worked perfectly, everything still runs on my side.

**Comment by codedust** [comment]
Nice to hear that :)
