### ISSUE TITLE
Detection of when a file has been completely sent doesn't work for small files

### ISSUE THREAD

**Issue by xamino** [codedust/go-tox#5]
Hello!

I have run into the problem that when sending small files (more specifically I believe files that fit within a single chunk) the detection of when a file has been completely sent as implemented here https://github.com/codedust/go-tox/blob/master/examples/example.go#L202 doesn't trigger. In my case this results in a number of transfers remaining open as they are never closed (and a bunch of clean up work going undone :stuck_out_tongue:  ).

So my question is how I can detect the successful sending of any sized file? I could check the file length against a chunk size limit to see if I'll only be sending the one chunk, but this limit is not exposed by gotox that I can see. Alternatively am I supposed to send a FileControl CANCEL on completing a transfer? That would mean cancel isn't named quite correctly (which would be a problem with ToxCore itself I think since they named it thus).

I'd appreciate a pointer towards a "reliable" solution. Thanks!

**Comment by codedust** [comment]
Hi!

I couldn't reproduce the behavior (even file transfer with file sizes of one or two bytes file length works fine for me).
In `example.go`, I get `File transfer completed (sending)` which indicates that the file handle has been closed.

Sending a FileControl shouldn't be necessary. According to the documentation in `tox.h`, comparing length with zero should be the correct way of detecting successful file transfers:

> If the length parameter is 0, the file transfer is finished, and the client's
> resources associated with the file number should be released.

However, there might be a problem when receiving files. I noticed that there probably is a bug in [line 247 in example.go](https://github.com/codedust/go-tox/blob/master/examples/example.go#L247):

```
-   if position == transfersFilesizes[fileNumber] {
+   if position + uint64(len(data)) >= transfersFilesizes[fileNumber] {
```

Could you test this in you environment where the error occoured?

---

EDIT: I updated example.go and added a little explanation. https://github.com/codedust/go-tox/commit/d4c7757e7a072a7fc0360a504fd75b1945102ec3#diff-2c82519cb986d2506f78f266b497be3eL227
The file handle will now be closed when the last chunk [EDIT] containing real data [/EDIT] is received (this will not require the zero-length chunk to be sent by the sender any more). The zero-lenth chunk will [now be ignored](https://github.com/codedust/go-tox/commit/d4c7757e7a072a7fc0360a504fd75b1945102ec3#diff-2c82519cb986d2506f78f266b497be3eR233).

**Comment by xamino** [comment]
I've checked my program for your possible solution. However it did not solve the problem, instead the receiver now closes transfers before the last chunk is received (the chunk with the position at the end of the file and len(data) == 0).

After quite a bit of playing around with the onFileChunkRequest() method, I've found a solution that works correctly from the application's view but goes contrary to how it should be. Here is the solution rewritten for example.go:

``` go
func onFileChunkRequest(t *gotox.Tox, friendNumber uint32, fileNumber uint32, position uint64, length uint64) {
    transfer, ok := transfers[fileNumber]
    if !ok {
        fmt.Println("Error: File handle does not exist")
        return
    }

    /* NOTE: missing IF statement for modifying length here, adapted and moved below! */

    if length == 0 {
        transfer.fileHandle.Close()
        delete(transfers, fileNumber)
        fmt.Println("File transfer completed (sending)", fileNumber)
        return
    }

    data := make([]byte, length)
    _, err := transfers[fileNumber].fileHandle.ReadAt(data, int64(position))
    if err != nil {
        fmt.Println("Error reading file", err)
    }

    t.FileSendChunk(friendNumber, fileNumber, position, data)

    /* NOTE: this is the new and I believe corrected statement, AFTER the last chunk is sent: */
    if length+position >=  transfer.fileSize {
        transfer.fileHandle.Close()
        delete(transfers, fileNumber)
        fmt.Println("File transfer completed (sending)", fileNumber)
        return
       }
}
```

Basically the change is this: if length + position is greater **or equal** than the file size, the transfer is done, but the last chunk must still be sent, so check this after sending the chunk.

Currently in the case that the [IF statement in line 210](https://github.com/codedust/go-tox/blob/master/examples/example.go#L210) is triggered (which is not often enough because I think it should be >= not just > ), the last chunk must still be sent - which it does, but it fails to close the transfer because length is not zero afterwards. Since the transfer is done, the method is not called again for that fileNumber, resulting in the transfer never being closed.

If you want to look at the code as it works right now in my application, you can check it out [here](https://github.com/Tinzenite/channel/blob/master/channel.go#L567) (I'd advice against executing it though, it's absolutely not done yet, although nothing should explode).

I'm not quite sure why this solution works for me even though ToxCore states it should work with length == 0. I'm looking forward to your feedback!

**Comment by codedust** [comment]
The last chunk len(data) == 0 is used to inform clients that _a stream_ has ended. For files with a fixed length this last chunk is not needed (see [line 233](https://github.com/codedust/go-tox/blob/master/examples/example.go#L233)).

> For files with known size, core will know that the transfer is complete after the last byte has been received, so it is not necessary (though not harmful) to send a zero-length chunk to terminate.

That's why I changed [line 247 in `onFileRecvChunk()`](https://github.com/codedust/go-tox/blob/master/examples/example.go#L247). We have to close the file handle even if we do not get a zero-length chunk. The file transfer is complete if `position + uint64(len(data)) >= transfer.fileSize`. The statement `position == transfer.fileSize` will only be `true` when the sender sends an additional zero-length chunk after the last chunk containing data. Please fix https://github.com/Tinzenite/channel/blob/master/channel.go#L541 according to [line 247](https://github.com/codedust/go-tox/blob/master/examples/example.go#L247).

In `onFileChunkRequest()`, it's important to **wait for the zero-length chunk** because sending the last bytes of data could fail. In this case the receiver would ask for the last few bytes again.
After receiving the whole file **the receiver** sends a zero-length chunk **to the sender** (we don't have to care about that. That's handled by toxcore internally). However there is no need for **the sender** to send a zero-length chunk.

The if statement in [line 210](https://github.com/codedust/go-tox/blob/master/examples/example.go#L210) is intended to ensure that position+length does not exceed the file boundaries (and avoid the resulting read error when calling `ReadAt`). When the receiver behaves correctly, `length+position > transfer.fileSize` should never be `true`. When `length+position == transfer.fileSize`, `length` is already `transfer.fileSize - position`, so `>=` should not be necessary.
I'll remove this if statement tomorrow (don't want to mess up with the line numbers again for today :D)

**Comment by xamino** [comment]
All right, I've changed it accordingly [here](https://github.com/Tinzenite/channel/blob/539b78b1c331fae06ad324280ae2ad45c23e7e4d/channel.go#L545).

Concerning this part:

> After receiving the whole file the **receiver sends a zero-length chunk to the sender** (we don't have to care about that. That's handled by toxcore internally).

Does that mean that I may have to close a _sending_ transfer upon _receiving a chunk_ on the sender's side? Because that I have not implemented and may explain why transfers go unclosed. That said, I checked, and the sender does not receive any chunks ever when sending files. If just ToxCore gets those zero length chunks, then how will I ever get notified that the transfer is complete if it isn't passed to me? :stuck_out_tongue: 

Thank you for your help so far in any case!

**Comment by codedust** [comment]
Sorry. That was not correct. I meant: "After receiving the whole file the receiver sends a zero-length chunk **request** to the sender". As you can see below, the receiver (toxcore) sends a zero-length chunk **request** as the last request when receiving a file:

> New message from 0 : /file
> File size is  38693
> onFileChunkRequest fileNumber: 0 position: 0 length: 1371
> onFileChunkRequest fileNumber: 0 position: 1371 length: 1371
> onFileChunkRequest fileNumber: 0 position: 2742 length: 1371
> ...
> onFileChunkRequest fileNumber: 0 position: 35646 length: 1371
> onFileChunkRequest fileNumber: 0 position: 37017 length: 1371
> onFileChunkRequest fileNumber: 0 position: 38388 length: 305
> onFileChunkRequest fileNumber: 0 position: 38693 length: 0  <--- zero-length chunk request
> File transfer completed (sending) 0

We wait for this last zero-length request and will then close the file handle (this is done in [line 214](https://github.com/codedust/go-tox/blob/master/examples/example.go#L214)).

BTW: It might be a good idea to send a TOX_FILE_CONTROL_CANCEL when [rejecting file transfers](https://github.com/Tinzenite/channel/blob/539b78b1c331fae06ad324280ae2ad45c23e7e4d/channel.go#L501) (see https://github.com/codedust/WebTox/blob/master/server/toxCallbacks.go#L121).

**Comment by xamino** [comment]
> BTW: It might be a good idea to send a TOX_FILE_CONTROL_CANCEL when rejecting file transfers (see https://github.com/codedust/WebTox/blob/master/server/toxCallbacks.go#L121).

Thanks, done.

> We wait for this last zero-length request and will then close the file handle (this is done in line 214).

This gave me an idea. I may be closing the receiving client too fast (and due to another bug incorrectly), which could result in ToxCore never getting the chance to send the last chunk.

I'll post again once I've confirmed if that may be the problem. Sadly testing takes a while because restarting the application means that the peers have to detect that the other peer is online every time, and that can take a few minutes each time...

EDIT: Yup, my error. I closed the receiving client immediately once the transfer was complete. Seems like ToxCore requires a few more rounds of tox.Iterate() to send the final chunk requests. I'll work around this by delaying the closing of the client.

Thank you for your help once again!

**Comment by codedust** [comment]
You might improve startup performance when bootstrapping to more than one node. Bootstapping should also be done every time your application starts, not only when creating the tox profile.

**Comment by xamino** [comment]
Wow, that was simple. Thank you for pointing that out! Not sure where I got the idea that that should only be done when creating a profile. It is a lot snappier now!

**Comment by codedust** [comment]
Great! Could you confirm the "file-handle-not-closed" issue is solved now?

Thanks for debugging!

**Comment by xamino** [comment]
Sure:

The issue was at its core that ToxCore requires a few additional iterations once files have been successfully received to notify the sender of the successful transfer (meaning the chunk request with zero length is sent at the earliest on the next tox.Iterate() call). In my case I closed the client immediately once the files were received before the receiver could notify the sender (before any further calls to tox.Iterate()). Adding a slight delay before closing the client fixed the issue in my application ([relevant commit](https://github.com/Tinzenite/tin/commit/90ce7070d0d57505ef9d8491b54f67e8a879d985)). Alternatively manually calling tox.Iterate() could also solve the issue, although I have not confirmed how many iterations it would require (just once for all outstanding files, once for each outstanding files, or some random amount depending on network speed).

EDIT: Also, to be clear on the transfer file size issue: that had no relevance, it was simply randomly always for small files that the issue happened in my application due to the order of sending files.

> Thanks for debugging!

For debugging my own application? Sure, you're welcome. :wink: But thank _you_ for your patience with me and your help. Here is hoping all further bugs have only myself to blame from the get go!

**Comment by codedust** [comment]
> For debugging my own application?

For debugging file transfers in gotox. ;)
